version: '3.8'

services:
  app:
    build:
      context: ./devcontainer
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.1"
        NODE_VERSION: "lts/gallium"
        MYSQL_HOST: db
        MYSQL_USER: mariadb
        MYSQL_PWD: mariadb
        MYSQL_DB_NAME: mariadb
        MYSQL_ROOT_PWD: mariadb
        SIDEA_DEVCONTAINER_VERSION: development
    volumes:
      - ./workspace/:/workspace:cached
      - ./.devcontainer:/workspace/.devcontainer
      - ./.vscode:/workspace/.vscode
    entrypoint: ["/bin/sh", "-c", "echo Container started\n
      trap \"exit 0\" 15\n
      \n
      exec \"$$@\"\n
      while sleep 1 & wait $$!; do :; done", "-", "docker-php-entrypoint"]
