version: '3.8'

services:
  app:
    build:
      context: devcontainer
      dockerfile: Dockerfile
      args:
        VARIANT: "8.1"
        NODE_VERSION: "lts/gallium"
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_PWD: mariadb
    volumes:
      - .:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  pma:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: mariadb
      PMA_PASSWORD: mariadb
    ports:
      - 8888:80

volumes:
  mariadb-data: